### ISSUE TITLE
执行 docker compose up 时报告错误

### ISSUE THREAD

**Issue by BONESDAO** [cnsilvan/node-x#1]
错误信息如下：

sample_validator  | Error: exit status 2
sample_validator  | 5:45PM ERR error="exit status 2" module=cosmovisor

然后就无法使用后续的内容了。

**Comment by cnsilvan** [comment]
哪一个项目

**Comment by BONESDAO** [comment]
allora network，他们更新版本了，我已经解决，谢谢
